name: Bug Report
description: Report a reproducible bug in SWE-AF
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce quickly.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps, commands, and inputs.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include OS, Python version, provider, and deployment mode.
      placeholder: |
        - OS:
        - Python:
        - AI provider:
        - Docker or local:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Trace
      description: Paste relevant logs or stack traces.
      render: shell
